In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from pandas import read_csv

In [4]:
address = '~/Downloads/iris.csv'
iris = pd.read_csv(address)
iris.head(10)

,refId,messageId,app,appContext,language,country,senderRole,recipientRole,advertiserId,conversationRef,imported,opened,answer,expert,action?,sub class,count
0,10692955-8,<CAFn6ztApk7U2Grs=2m_31MaQ15HeXNhLJmxrLhm2ccAF...,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,10692955,<1b7dm4eel29h084r@indeedemail.com>,1,0,yes-request,alexw,action,confirm-interest,1
1,3102284-167,<CAN74uq0z42mPZP5A8t5rZwh8Zf87U56wyvP7zJuTJz_s...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,3102284,<1bejm0mt02t8rbge@indeedemail.com>,1,1,yes-request,jha,action,confirm-interest,1
2,6472919-7404,<MWHPR03MB30708CAFAABF39F20BC43D23A2AC0@MWHPR0...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,6472919,<1bekdr8qq2t8rcqc@indeedemail.com>,1,1,yes-request,emaxwell,action,answer-questions,1
3,7983078-195,<CAFdonBzOSkow1Jnjepfo0oXPc8M_2LQwwxOi0cUNC5wH...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,7983078,<1bg1rcieq2suvfbe@indeedemail.com>,1,0,yes-request,emaxwell,action,answer-questions,1
4,5805740-3759,<BN6PR08MB25300D48A531251470C9C642BD780@BN6PR0...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,5805740,<1bgbpbj2o2suvb7b@indeedemail.com>,1,0,yes-request,emaxwell,action,confirm-one-option,1
5,5941549-845,<01d301d30fbf$58a47760$09ed6620$@com>,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,5941549,<1bf1tifc40c8p4ca@indeedemail.com>,1,0,yes-request,jha,action,apply-online,1
6,6505112-804,<DM5PR13MB13698F08AC7ECD696BD3C525BB840@DM5PR1...,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,6505112,<1bgocmjcl2suvf6l@indeedemail.com>,1,1,yes-request,jha,action,confirm-interest,1
7,12696619-470,<SN1PR0801MB156808B3594C717892E930D7B3910@SN1P...,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,12696619,<1bh38n4ue2stiek4@indeedemail.com>,1,1,yes-request,jha,action,apply-online,1
8,12891144-149,<CAJMvtewSm8_r2uo1Ykh0B5TCbrW8Q0TNgnw7kd-q=Ky4...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,12891144,<1bhustq4d2stib4v@indeedemail.com>,1,1,no-request,jha,noaction,marketing-spam},1
9,11931275-20,<1016025201.242192.1499973880814@email.1and1.c...,DRADIS,dradis-reply,en,CA,EMPLOYER,JOBSEEKER,11931275,<1bhlfjju429klb1m684362122668@indeedemail.com>,1,1,yes-request,jha,action,other,1

In [6]:
iris.isnull().any()

refId              False
messageId          False
app                False
appContext         False
language           False
country            False
senderRole         False
recipientRole      False
advertiserId       False
conversationRef    False
imported           False
opened             False
answer             False
expert             False
action?            False
sub class          False
count              False
dtype: bool

In [20]:
iris_trim = iris[['app', 'appContext', 'language', 'country', 'senderRole', 'recipientRole', 'imported', 'opened', 'answer', 'action?', 'sub class']]

In [21]:
iris_trim.head(20)

,app,appContext,language,country,senderRole,recipientRole,imported,opened,answer,action?,sub class
0,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,1,0,yes-request,action,confirm-interest
1,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,1,yes-request,action,confirm-interest
2,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,1,yes-request,action,answer-questions
3,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,0,yes-request,action,answer-questions
4,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,0,yes-request,action,confirm-one-option
5,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,0,yes-request,action,apply-online
6,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,1,1,yes-request,action,confirm-interest
7,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,1,1,yes-request,action,apply-online
8,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,1,no-request,noaction,marketing-spam}
9,DRADIS,dradis-reply,en,CA,EMPLOYER,JOBSEEKER,1,1,yes-request,action,other
10,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,1,no-request,noaction,marketing-spam}
11,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,1,no-request,"{""norequest""",marketing-spam}
12,DRADIS,dradis-reply,en,US,EMPLOYER,JOBSEEKER,0,1,yes-request,action,confirm-interest
13,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,1,no-request,"{""norequest""",marketing-spam}
14,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,1,yes-request,action,confirm-one-option
15,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,1,yes-request,action,apply-online
16,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,1,yes-request,action,confirm-interest
17,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,1,1,yes-request,action,appear-in-person
18,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,1,yes-request,action,confirm-multiple-options
19,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,1,1,no-request,noaction,other}

In [25]:
iris_trim.groupby('sub class').describe()

                                                   imported            \
                                                      count      mean
sub class
accept-invite                                          18.0  0.333333
answer-questions                                      370.0  0.370270
appear-in-person                                      296.0  0.165541
application-receipt                                     2.0  1.000000
application-receipt,"userReason"                        1.0  1.000000
application-receipt}                                  226.0  0.544248
apply-online                                          609.0  0.243021
confirm-interest                                      607.0  0.242175
confirm-multiple-options                              151.0  0.298013
confirm-one-option                                    261.0  0.333333
email-someone-else                                    107.0  0.158879
marketing-spam                                          2.0  0.000000
marketing-spam}                                        45.0  0.466667
mutually-schedule                                     385.0  0.374026
other                                                  42.0  0.666667
other,"userReason"                                      5.0  1.000000
other,"userReason"This is an email from the job...      1.0  1.000000
other}                                                 49.0  0.816327
rejection                                               1.0  0.000000
rejection,"userReason"                                  1.0  0.000000

                                                                             \
                                                         std  min  25%  50%
sub class
accept-invite                                       0.485071  0.0  0.0  0.0
answer-questions                                    0.483531  0.0  0.0  0.0
appear-in-person                                    0.372297  0.0  0.0  0.0
application-receipt                                 0.000000  1.0  1.0  1.0
application-receipt,"userReason"                         NaN  1.0  1.0  1.0
application-receipt}                                0.499144  0.0  0.0  1.0
apply-online                                        0.429260  0.0  0.0  0.0
confirm-interest                                    0.428753  0.0  0.0  0.0
confirm-multiple-options                            0.458907  0.0  0.0  0.0
confirm-one-option                                  0.480384  0.0  0.0  0.0
email-someone-else                                  0.367283  0.0  0.0  0.0
marketing-spam                                      0.000000  0.0  0.0  0.0
marketing-spam}                                     0.504525  0.0  0.0  0.0
mutually-schedule                                   0.484500  0.0  0.0  0.0
other                                               0.477119  0.0  0.0  1.0
other,"userReason"                                  0.000000  1.0  1.0  1.0
other,"userReason"This is an email from the job...       NaN  1.0  1.0  1.0
other}                                              0.391230  0.0  1.0  1.0
rejection                                                NaN  0.0  0.0  0.0
rejection,"userReason"                                   NaN  0.0  0.0  0.0

                                                             opened            \
                                                    75%  max  count      mean
sub class
accept-invite                                       1.0  1.0   18.0  0.666667
answer-questions                                    1.0  1.0  370.0  0.772973
appear-in-person                                    0.0  1.0  296.0  0.652027
application-receipt                                 1.0  1.0    2.0  1.000000
application-receipt,"userReason"                    1.0  1.0    1.0  1.000000
application-receipt}                                1.0  1.0  226.0  0.747788
apply-online                                        0.0  1.0  609.0  0.691297
confirm-interest                                    0.0  1.0  607.0  0.698517
confirm-multiple-options                            1.0  1.0  151.0  0.695364
confirm-one-option                                  1.0  2.0  261.0  0.731801
email-someone-else                                  0.0  1.0  107.0  0.700935
marketing-spam                                      0.0  0.0    2.0  1.000000
marketing-spam}                                     1.0  1.0   45.0  0.600000
mutually-schedule                                   1.0  1.0  385.0  0.735065
other                                               1.0  1.0   42.0  0.833333
other,"userReason"                                  1.0  1.0    5.0  0.800000
other,"userReason"This is an email from the job...  1.0  1.0    1.0  0.000000
other}                                              1.0  1.0   49.0  0.816327
rejection                                           0.0  0.0    1.0  1.000000
rejection,"userReason"                              0.0  0.0    1.0  1.000000

                                                                              \
                                                         std  min   25%  50%
sub class
accept-invite                                       0.485071  0.0  0.00  1.0
answer-questions                                    0.419477  0.0  1.00  1.0
appear-in-person                                    0.477134  0.0  0.00  1.0
application-receipt                                 0.000000  1.0  1.00  1.0
application-receipt,"userReason"                         NaN  1.0  1.00  1.0
application-receipt}                                0.435247  0.0  0.25  1.0
apply-online                                        0.462338  0.0  0.00  1.0
confirm-interest                                    0.459280  0.0  0.00  1.0
confirm-multiple-options                            0.461785  0.0  0.00  1.0
confirm-one-option                                  0.452455  0.0  0.00  1.0
email-someone-else                                  0.460003  0.0  0.00  1.0
marketing-spam                                      0.000000  1.0  1.00  1.0
marketing-spam}                                     0.495434  0.0  0.00  1.0
mutually-schedule                                   0.441873  0.0  0.00  1.0
other                                               0.377195  0.0  1.00  1.0
other,"userReason"                                  0.447214  0.0  1.00  1.0
other,"userReason"This is an email from the job...       NaN  0.0  0.00  0.0
other}                                              0.391230  0.0  1.00  1.0
rejection                                                NaN  1.0  1.00  1.0
rejection,"userReason"                                   NaN  1.0  1.00  1.0


                                                    75%  max
sub class
accept-invite                                       1.0  1.0
answer-questions                                    1.0  1.0
appear-in-person                                    1.0  1.0
application-receipt                                 1.0  1.0
application-receipt,"userReason"                    1.0  1.0
application-receipt}                                1.0  1.0
apply-online                                        1.0  1.0
confirm-interest                                    1.0  1.0
confirm-multiple-options                            1.0  1.0
confirm-one-option                                  1.0  2.0
email-someone-else                                  1.0  1.0
marketing-spam                                      1.0  1.0
marketing-spam}                                     1.0  1.0
mutually-schedule                                   1.0  1.0
other                                               1.0  1.0
other,"userReason"                                  1.0  1.0
other,"userReason"This is an email from the job...  0.0  0.0
other}                                              1.0  1.0
rejection                                           1.0  1.0
rejection,"userReason"                              1.0  1.0

In [26]:
iris_trim.groupby('appContext').describe()

                  imported                                               \
                     count      mean       std  min  25%  50%  75%  max
appContext
application-email    957.0  1.001045  0.032325  1.0  1.0  1.0  1.0  2.0
dradis-reply           9.0  0.111111  0.333333  0.0  0.0  0.0  0.0  1.0
dradis-send         2196.0  0.019126  0.136998  0.0  0.0  0.0  0.0  1.0
mobile-send           17.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0

                   opened
                    count      mean       std  min  25%  50%  75%  max
appContext
application-email   957.0  0.781609  0.415893  0.0  1.0  1.0  1.0  2.0
dradis-reply          9.0  1.000000  0.000000  1.0  1.0  1.0  1.0  1.0
dradis-send        2196.0  0.683971  0.465030  0.0  0.0  1.0  1.0  1.0
mobile-send          17.0  0.764706  0.437237  0.0  1.0  1.0  1.0  1.0

In [27]:
address = '~/Downloads/depth_iris.csv'
depth_iris = pd.read_csv(address)
depth_iris.head(10)

,refId[1000],counts,appContext,jobseekerOpenedCount,jobseekerOpenedCount/counts,depth>0,depth>0/counts,depth>1,depth=0/counts,depth=1/counts,depth=2/counts,depth=3/counts,depth=4/counts,depth>4/counts
0,15262879-203,2569,0,10,0.003893,2565,0.998443,2,0.001557,0.997665,0.000779,0.0,0.0,0.0
1,EMPTY,1999,0,0,0.000000,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0
2,712929,1448,0,153,0.105663,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0
3,1057627,1093,0,0,0.000000,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0
4,1696336-125,737,0,215,0.291723,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0
5,38448,566,0,105,0.185512,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0
6,557738,556,0,58,0.104316,1,0.001799,0,0.998201,0.001799,0.000000,0.0,0.0,0.0
7,28377-29880,541,0,0,0.000000,539,0.996303,0,0.003697,0.996303,0.000000,0.0,0.0,0.0
8,1959998-4,358,0,0,0.000000,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0
9,1532945,337,0,24,0.071217,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0

In [28]:
address = '~/Downloads/imported.csv'
imported_iris = pd.read_csv(address)
imported_iris.head(10)

     refId[1000]  appContext  imported
0   15262879-203           0      5135
1         880010           0      2992
2            NaN           0      1999
3  4006046-23080           0      1460
4         712929           0      1448
5        1057627           0      1093
6    28377-29880           0      1079
7    1696336-125           0       737
8     2654313-53           0       672
9          38448           0       566

In [29]:
print(imported_iris.index)

RangeIndex(start=0, stop=1000, step=1)

In [32]:
print(depth_iris.index)

RangeIndex(start=0, stop=1000, step=1)

In [33]:
imp = imported_iris

In [36]:
imp.set_index('refId[1000]', inplace=True)

Index([ '15262879-203',        '880010',             nan, '4006046-23080',
              '712929',       '1057627',   '28377-29880',   '1696336-125',
          '2654313-53',         '38448',
       ...
       '6984427-11765', '6984427-15057', '6984427-11065', '6984427-15113',
       '6984427-15529', '6984427-11835', '6984427-11758', '6984427-11519',
       '6984427-11466', '6984427-14545'],
      dtype='object', name='refId[1000]', length=1000)

In [37]:
print(imp.index)

In [38]:
depth = depth_iris

In [39]:
depth.set_index('refId[1000]', inplace=True)

In [40]:
print(depth.index)

Index(['15262879-203', 'EMPTY', '712929', '1057627', '1696336-125', '38448',
       '557738', '28377-29880', '1959998-4', '1532945',
       ...
       '6061935-21', '2453043-352', '4195032-205', '4679527-163',
       '4679527-164', '5994087-133', '5982561-24', '5954960-165',
       '1683590-8413', '5954960-174'],
      dtype='object', name='refId[1000]', length=1000)

In [41]:
imp.head(10)

               appContext  imported
refId[1000]
15262879-203            0      5135
880010                  0      2992
NaN                     0      1999
4006046-23080           0      1460
712929                  0      1448
1057627                 0      1093
28377-29880             0      1079
1696336-125             0       737
2654313-53              0       672
38448                   0       566

In [42]:
depth.head(10)

,counts,appContext,jobseekerOpenedCount,jobseekerOpenedCount/counts,depth>0,depth>0/counts,depth>1,depth=0/counts,depth=1/counts,depth=2/counts,depth=3/counts,depth=4/counts,depth>4/counts
refId[1000],,,,,,,,,,,,,
15262879-203,2569,0,10,0.003893,2565,0.998443,2,0.001557,0.997665,0.000779,0.0,0.0,0.0
EMPTY,1999,0,0,0.000000,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0
712929,1448,0,153,0.105663,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0
1057627,1093,0,0,0.000000,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0
1696336-125,737,0,215,0.291723,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0
38448,566,0,105,0.185512,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0
557738,556,0,58,0.104316,1,0.001799,0,0.998201,0.001799,0.000000,0.0,0.0,0.0
28377-29880,541,0,0,0.000000,539,0.996303,0,0.003697,0.996303,0.000000,0.0,0.0,0.0
1959998-4,358,0,0,0.000000,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0
1532945,337,0,24,0.071217,0,0.000000,0,1.000000,0.000000,0.000000,0.0,0.0,0.0

In [49]:
imp_sort = imp.sort_index(inplace=False)

In [51]:
imp_sort.head(20)

              appContext  imported
refId[1000]
10032555-313           0       252
10313292-348           0       359
1057627                0      1093
1066116                0       102
1076070                0       132
10862097-9             0       158
1097372                0       103
1274084                0       110
1280898                0       163
12911410-32            0       237
13298947-555           0       102
13592346-4             0       103
1364606                0       225
13689617-151           0       143
13925647-23            0       106
14089586-7             0       169
14302433-17            0        97
1455139                0       137
1466268-404            0       105
14940035-5             0       110

In [52]:
depth_sort = depth.sort_index(inplace=False)

In [53]:
depth_sort.head(20)

,counts,appContext,jobseekerOpenedCount,jobseekerOpenedCount/counts,depth>0,depth>0/counts,depth>1,depth=0/counts,depth=1/counts,depth=2/counts,depth=3/counts,depth=4/counts,depth>4/counts
refId[1000],,,,,,,,,,,,,
10032555-313,252,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
100870-278,43,0,1,0.023256,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
100870-345,43,0,2,0.046512,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
1018396,63,0,26,0.412698,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
1020211-1571,45,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
1031725-422,44,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
1051560-10,42,0,4,0.095238,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
1057627,1093,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
1066116,102,0,43,0.421569,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
1076070,132,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
10862097-9,158,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
1097372,103,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
10994757-32,43,0,6,0.139535,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
11091032-136,45,0,13,0.288889,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
111830-6880,74,0,2,0.027027,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
1120865-1094,41,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
11225174-7,69,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
1142866-525,43,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
11435771-21,45,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
11435771-7,58,0,9,0.155172,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0

In [55]:
leftmerge = depth_sort.merge(imp_sort, on='refId[1000]', how='left')

In [56]:
leftmerge.head(20)

,counts,appContext_x,jobseekerOpenedCount,jobseekerOpenedCount/counts,depth>0,depth>0/counts,depth>1,depth=0/counts,depth=1/counts,depth=2/counts,depth=3/counts,depth=4/counts,depth>4/counts,appContext_y,imported
refId[1000],,,,,,,,,,,,,,,
10032555-313,252,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,252.0
100870-278,43,0,1,0.023256,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
100870-345,43,0,2,0.046512,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1018396,63,0,26,0.412698,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1020211-1571,45,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1031725-422,44,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1051560-10,42,0,4,0.095238,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1057627,1093,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1093.0
1066116,102,0,43,0.421569,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,102.0
1076070,132,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,132.0
10862097-9,158,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,158.0
1097372,103,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,103.0
10994757-32,43,0,6,0.139535,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
11091032-136,45,0,13,0.288889,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
111830-6880,74,0,2,0.027027,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1120865-1094,41,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
11225174-7,69,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1142866-525,43,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
11435771-21,45,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
11435771-7,58,0,9,0.155172,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

In [57]:
rightmerge = depth_sort.merge(imp_sort, on='refId[1000]', how='right')

In [58]:
rightmerge.head(20)

,counts,appContext_x,jobseekerOpenedCount,jobseekerOpenedCount/counts,depth>0,depth>0/counts,depth>1,depth=0/counts,depth=1/counts,depth=2/counts,depth=3/counts,depth=4/counts,depth>4/counts,appContext_y,imported
refId[1000],,,,,,,,,,,,,,,
10032555-313,252.0,0.0,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,252
1057627,1093.0,0.0,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,1093
1066116,102.0,0.0,43.0,0.421569,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,102
1076070,132.0,0.0,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,132
10862097-9,158.0,0.0,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,158
1097372,103.0,0.0,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,103
1274084,110.0,0.0,18.0,0.163636,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,110
1280898,163.0,0.0,42.0,0.257669,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,163
13592346-4,100.0,0.0,0.0,0.000000,3.0,0.030000,0.0,0.970000,0.030000,0.000000,0.0,0.0,0.0,0,103
1364606,225.0,0.0,29.0,0.128889,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,225
1455139,137.0,0.0,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,137
1466268-404,105.0,0.0,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,105
15262879-203,2569.0,0.0,10.0,0.003893,2565.0,0.998443,2.0,0.001557,0.997665,0.000779,0.0,0.0,0.0,0,5135
1532945,337.0,0.0,24.0,0.071217,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,337
1569689-2190,185.0,0.0,2.0,0.010811,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,185
1626687,188.0,0.0,9.0,0.047872,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,188
1649639,133.0,0.0,1.0,0.007519,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,133
1696336-125,737.0,0.0,215.0,0.291723,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,737
1717974-203,132.0,0.0,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,132
1757841-281,131.0,0.0,3.0,0.022901,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0,131

In [59]:
rightmerge.describe()

,counts,appContext_x,jobseekerOpenedCount,jobseekerOpenedCount/counts,depth>0,depth>0/counts,depth>1,depth=0/counts,depth=1/counts,depth=2/counts,depth=3/counts,depth=4/counts,depth>4/counts,appContext_y,imported
count,121.000000,121.0,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,1000.0,1000.000000
mean,170.801653,0.0,14.975207,0.081981,27.851240,0.038984,1.206612,0.961016,0.028325,0.007779,0.000977,0.000946,0.000957,0.0,125.167000
std,286.015752,0.0,34.859830,0.183745,237.939511,0.172257,8.303531,0.172257,0.147721,0.066447,0.007185,0.007045,0.007323,0.0,210.593658
min,42.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.001557,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,58.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,100.000000
50%,107.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,102.000000
75%,156.000000,0.0,10.000000,0.079646,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,106.000000
max,2569.000000,0.0,215.000000,1.160714,2565.000000,0.998443,79.000000,1.000000,0.997665,0.718182,0.071429,0.071429,0.072165,0.0,5135.000000

In [60]:
leftmerge.describe()

,counts,appContext_x,jobseekerOpenedCount,jobseekerOpenedCount/counts,depth>0,depth>0/counts,depth>1,depth=0/counts,depth=1/counts,depth=2/counts,depth=3/counts,depth=4/counts,depth>4/counts,appContext_y,imported
count,1000.000000,1000.0,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,121.0,121.000000
mean,67.229000,0.0,4.218000,0.049800,3.430000,0.005819,0.168000,0.994181,0.004141,0.001066,0.000223,0.000150,0.000239,0.0,235.719008
std,123.393219,0.0,15.138416,0.146343,82.970412,0.064148,2.948639,0.064148,0.053206,0.023291,0.003776,0.002698,0.003856,0.0,503.138636
min,41.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.001557,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,43.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,108.000000
50%,48.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,130.000000
75%,56.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,169.000000
max,2569.000000,0.0,215.000000,1.160714,2565.000000,0.998443,79.000000,1.000000,0.997665,0.718182,0.087719,0.071429,0.087719,0.0,5135.000000

In [62]:
leftmerge.isnull().any()

counts                         False
appContext_x                   False
jobseekerOpenedCount           False
jobseekerOpenedCount/counts    False
depth>0                        False
depth>0/counts                 False
depth>1                        False
depth=0/counts                 False
depth=1/counts                 False
depth=2/counts                 False
depth=3/counts                 False
depth=4/counts                 False
depth>4/counts                 False
appContext_y                    True
imported                        True
dtype: bool

In [63]:
rightmerge.isnull().any()

counts                          True
appContext_x                    True
jobseekerOpenedCount            True
jobseekerOpenedCount/counts     True
depth>0                         True
depth>0/counts                  True
depth>1                         True
depth=0/counts                  True
depth=1/counts                  True
depth=2/counts                  True
depth=3/counts                  True
depth=4/counts                  True
depth>4/counts                  True
appContext_y                   False
imported                       False
dtype: bool

In [64]:
leftmerge.head(20)

,counts,appContext_x,jobseekerOpenedCount,jobseekerOpenedCount/counts,depth>0,depth>0/counts,depth>1,depth=0/counts,depth=1/counts,depth=2/counts,depth=3/counts,depth=4/counts,depth>4/counts,appContext_y,imported
refId[1000],,,,,,,,,,,,,,,
10032555-313,252,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,252.0
100870-278,43,0,1,0.023256,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
100870-345,43,0,2,0.046512,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1018396,63,0,26,0.412698,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1020211-1571,45,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1031725-422,44,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1051560-10,42,0,4,0.095238,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1057627,1093,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1093.0
1066116,102,0,43,0.421569,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,102.0
1076070,132,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,132.0
10862097-9,158,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,158.0
1097372,103,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,103.0
10994757-32,43,0,6,0.139535,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
11091032-136,45,0,13,0.288889,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
111830-6880,74,0,2,0.027027,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1120865-1094,41,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
11225174-7,69,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1142866-525,43,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
11435771-21,45,0,0,0.000000,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
11435771-7,58,0,9,0.155172,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

In [65]:
leftmerge.groupby('depth>0').describe()

        appContext_x                                    appContext_y       \
               count mean  std  min  25%  50%  75%  max        count mean
depth>0
0              974.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0        111.0  0.0
1               12.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0          2.0  0.0
2                2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0          0.0  NaN
3                3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0          1.0  0.0
5                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0  NaN
10               1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0  0.0
35               1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0  NaN
37               1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0  0.0
44               1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0  0.0
79               1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0  0.0
91               1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0  0.0
539              1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0  0.0
2565             1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0  0.0

           ...    jobseekerOpenedCount        jobseekerOpenedCount/counts  \
           ...                     75%    max                       count
depth>0    ...
0          ...                    0.00  215.0                       974.0
1          ...                   12.25   58.0                        12.0
2          ...                    1.50    2.0                         2.0
3          ...                   31.00   48.0                         3.0
5          ...                    0.00    0.0                         1.0
10         ...                    1.00    1.0                         1.0
35         ...                   45.00   45.0                         1.0
37         ...                   65.00   65.0                         1.0
44         ...                    0.00    0.0                         1.0
79         ...                    0.00    0.0                         1.0
91         ...                    0.00    0.0                         1.0
539        ...                    0.00    0.0                         1.0
2565       ...                   10.00   10.0                         1.0


             mean       std       min       25%       50%       75%       max
depth>0
0        0.046298  0.138164  0.000000  0.000000  0.000000  0.000000  0.977273
1        0.132258  0.158656  0.000000  0.013636  0.069474  0.261905  0.492064
2        0.019608  0.027730  0.000000  0.009804  0.019608  0.029412  0.039216
3        0.372636  0.411056  0.000000  0.152174  0.304348  0.558954  0.813559
5        0.000000       NaN  0.000000  0.000000  0.000000  0.000000  0.000000
10       0.007936       NaN  0.007936  0.007936  0.007936  0.007936  0.007936
35       0.789474       NaN  0.789474  0.789474  0.789474  0.789474  0.789474
37       1.160714       NaN  1.160714  1.160714  1.160714  1.160714  1.160714
44       0.000000       NaN  0.000000  0.000000  0.000000  0.000000  0.000000
79       0.000000       NaN  0.000000  0.000000  0.000000  0.000000  0.000000
91       0.000000       NaN  0.000000  0.000000  0.000000  0.000000  0.000000
539      0.000000       NaN  0.000000  0.000000  0.000000  0.000000  0.000000
2565     0.003893       NaN  0.003893  0.003893  0.003893  0.003893  0.003893

[13 rows x 112 columns]

In [66]:
leftmerge.groupby('depth>0/counts').describe()

               appContext_x                                    appContext_y  \
                      count mean  std  min  25%  50%  75%  max        count
depth>0/counts
0.000000              974.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0        111.0
0.001799                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0
0.004546                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0
0.013333                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0
0.015873                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0
0.018182                2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0          0.0
0.018519                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0
0.018868                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0
0.019608                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0
0.023256                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0
0.023810                2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0          0.0
0.030000                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0
0.039216                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0
0.044444                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0
0.050848                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0
0.065217                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0
0.079365                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0
0.094340                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0
0.469072                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0
0.614035                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          0.0
0.660714                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0
0.718182                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0
0.758621                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0
0.996303                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0
0.998443                1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0          1.0

                       ...    jobseekerOpenedCount         \
               mean    ...                     75%    max
depth>0/counts         ...
0.000000        0.0    ...                    0.00  215.0
0.001799        0.0    ...                   58.00   58.0
0.004546        0.0    ...                    9.00    9.0
0.013333        NaN    ...                    0.00    0.0
0.015873        NaN    ...                   31.00   31.0
0.018182        NaN    ...                   12.25   16.0
0.018519        NaN    ...                    0.00    0.0
0.018868        NaN    ...                    1.00    1.0
0.019608        NaN    ...                    5.00    5.0
0.023256        NaN    ...                    0.00    0.0
0.023810        NaN    ...                   11.00   11.0
0.030000        0.0    ...                    0.00    0.0
0.039216        NaN    ...                    2.00    2.0
0.044444        NaN    ...                    0.00    0.0
0.050848        NaN    ...                   48.00   48.0
0.065217        NaN    ...                   14.00   14.0
0.079365        0.0    ...                    1.00    1.0
0.094340        NaN    ...                    0.00    0.0
0.469072        0.0    ...                    0.00    0.0
0.614035        NaN    ...                   45.00   45.0
0.660714        0.0    ...                   65.00   65.0
0.718182        0.0    ...                    0.00    0.0
0.758621        0.0    ...                    0.00    0.0
0.996303        0.0    ...                    0.00    0.0
0.998443        0.0    ...                   10.00   10.0

               jobseekerOpenedCount/counts                                \
                                     count      mean       std       min
depth>0/counts
0.000000                             974.0  0.046298  0.138164  0.000000
0.001799                               1.0  0.104316       NaN  0.104316
0.004546                               1.0  0.040909       NaN  0.040909
0.013333                               1.0  0.000000       NaN  0.000000
0.015873                               1.0  0.492064       NaN  0.492064
0.018182                               2.0  0.154545  0.192847  0.018182
0.018519                               1.0  0.000000       NaN  0.000000
0.018868                               1.0  0.018868       NaN  0.018868
0.019608                               1.0  0.098039       NaN  0.098039
0.023256                               1.0  0.000000       NaN  0.000000
0.023810                               2.0  0.261905  0.000000  0.261905
0.030000                               1.0  0.000000       NaN  0.000000
0.039216                               1.0  0.039216       NaN  0.039216
0.044444                               1.0  0.000000       NaN  0.000000
0.050848                               1.0  0.813559       NaN  0.813559
0.065217                               1.0  0.304348       NaN  0.304348
0.079365                               1.0  0.007936       NaN  0.007936
0.094340                               1.0  0.000000       NaN  0.000000
0.469072                               1.0  0.000000       NaN  0.000000
0.614035                               1.0  0.789474       NaN  0.789474
0.660714                               1.0  1.160714       NaN  1.160714
0.718182                               1.0  0.000000       NaN  0.000000
0.758621                               1.0  0.000000       NaN  0.000000
0.996303                               1.0  0.000000       NaN  0.000000
0.998443                               1.0  0.003893       NaN  0.003893


                     25%       50%       75%       max
depth>0/counts
0.000000        0.000000  0.000000  0.000000  0.977273
0.001799        0.104316  0.104316  0.104316  0.104316
0.004546        0.040909  0.040909  0.040909  0.040909
0.013333        0.000000  0.000000  0.000000  0.000000
0.015873        0.492064  0.492064  0.492064  0.492064
0.018182        0.086364  0.154545  0.222727  0.290909
0.018519        0.000000  0.000000  0.000000  0.000000
0.018868        0.018868  0.018868  0.018868  0.018868
0.019608        0.098039  0.098039  0.098039  0.098039
0.023256        0.000000  0.000000  0.000000  0.000000
0.023810        0.261905  0.261905  0.261905  0.261905
0.030000        0.000000  0.000000  0.000000  0.000000
0.039216        0.039216  0.039216  0.039216  0.039216
0.044444        0.000000  0.000000  0.000000  0.000000
0.050848        0.813559  0.813559  0.813559  0.813559
0.065217        0.304348  0.304348  0.304348  0.304348
0.079365        0.007936  0.007936  0.007936  0.007936
0.094340        0.000000  0.000000  0.000000  0.000000
0.469072        0.000000  0.000000  0.000000  0.000000
0.614035        0.789474  0.789474  0.789474  0.789474
0.660714        1.160714  1.160714  1.160714  1.160714
0.718182        0.000000  0.000000  0.000000  0.000000
0.758621        0.000000  0.000000  0.000000  0.000000
0.996303        0.000000  0.000000  0.000000  0.000000
0.998443        0.003893  0.003893  0.003893  0.003893

[25 rows x 112 columns]

In [ ]:
##Working... here

#R Correlation
pearsonr_coefficient, p_value = pearsonr(leftmerge.depth>0/counts, indeed.revenue2)
print('PearsonR Correlation Coefficient %0.3f' % (pearsonr_coefficient))

              appContext  imported
refId[1000]
10032555-313           0       252
10313292-348           0       359
1057627                0      1093
1066116                0       102
1076070                0       132
10862097-9             0       158
1097372                0       103
1274084                0       110
1280898                0       163
12911410-32            0       237
13298947-555           0       102
13592346-4             0       103
1364606                0       225
13689617-151           0       143
13925647-23            0       106
14089586-7             0       169
14302433-17            0        97
1455139                0       137
1466268-404            0       105
14940035-5             0       110

In [ ]:
imp_sort = imp.sort_values(by)

In [15]:
iris2.head(20)

,refid,messageld,app,appContext,language,country,senderRole,recipientRole,advertiserid,conversationRef,imported,opened,answer,expert,action,subClass,count
0,NaN,NaN,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,NaN,<1b7dm4eel29h084r@indeedemail.com>,1,0,yes-request,alexw,NaN,NaN,1
1,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bejm0mt02t8rbge@indeedemail.com>,1,1,yes-request,jha,NaN,NaN,1
2,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bekdr8qq2t8rcqc@indeedemail.com>,1,1,yes-request,emaxwell,NaN,NaN,1
3,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bg1rcieq2suvfbe@indeedemail.com>,1,0,yes-request,emaxwell,NaN,NaN,1
4,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bgbpbj2o2suvb7b@indeedemail.com>,1,0,yes-request,emaxwell,NaN,NaN,1
5,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bf1tifc40c8p4ca@indeedemail.com>,1,0,yes-request,jha,NaN,NaN,1
6,NaN,NaN,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,NaN,<1bgocmjcl2suvf6l@indeedemail.com>,1,1,yes-request,jha,NaN,NaN,1
7,NaN,NaN,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,NaN,<1bh38n4ue2stiek4@indeedemail.com>,1,1,yes-request,jha,NaN,NaN,1
8,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bhustq4d2stib4v@indeedemail.com>,1,1,no-request,jha,NaN,NaN,1
9,NaN,NaN,DRADIS,dradis-reply,en,CA,EMPLOYER,JOBSEEKER,NaN,<1bhlfjju429klb1m684362122668@indeedemail.com>,1,1,yes-request,jha,NaN,NaN,1
10,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bigjilgn2te79g1@indeedemail.com>,1,1,no-request,jha,NaN,NaN,1
11,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bhustq4d2stib4v@indeedemail.com>,1,1,no-request,jha,NaN,NaN,1
12,NaN,NaN,DRADIS,dradis-reply,en,US,EMPLOYER,JOBSEEKER,NaN,<1bi73uus1324va5r3f3f8948aee1@indeedemail.com>,0,1,yes-request,jha,NaN,NaN,1
13,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bigjilgn2te79g1@indeedemail.com>,1,1,no-request,jha,NaN,NaN,1
14,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bj0hiec62te7fdd@indeedemail.com>,1,1,yes-request,jha,NaN,NaN,1
15,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bj0ndjsu2te79g4@indeedemail.com>,1,1,yes-request,jha,NaN,NaN,1
16,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bj53jvbg08v11j0@indeedemail.com>,1,1,yes-request,jha,NaN,NaN,1
17,NaN,NaN,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,NaN,<1bj6avl8e08v161f@indeedemail.com>,1,1,yes-request,jha,NaN,NaN,1
18,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bj8istph2te7bub@indeedemail.com>,1,1,yes-request,jha,NaN,NaN,1
19,NaN,NaN,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,NaN,<1bjtdjk6608v14r6@indeedemail.com>,1,1,no-request,jha,NaN,NaN,1

,refId,messageId,app,appContext,language,country,senderRole,recipientRole,advertiserId,conversationRef,imported,opened,answer,expert,action?,sub class,count
0,10692955-8,<CAFn6ztApk7U2Grs=2m_31MaQ15HeXNhLJmxrLhm2ccAF...,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,10692955,<1b7dm4eel29h084r@indeedemail.com>,1,0,yes-request,alexw,action,confirm-interest,1
1,3102284-167,<CAN74uq0z42mPZP5A8t5rZwh8Zf87U56wyvP7zJuTJz_s...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,3102284,<1bejm0mt02t8rbge@indeedemail.com>,1,1,yes-request,jha,action,confirm-interest,1
2,6472919-7404,<MWHPR03MB30708CAFAABF39F20BC43D23A2AC0@MWHPR0...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,6472919,<1bekdr8qq2t8rcqc@indeedemail.com>,1,1,yes-request,emaxwell,action,answer-questions,1
3,7983078-195,<CAFdonBzOSkow1Jnjepfo0oXPc8M_2LQwwxOi0cUNC5wH...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,7983078,<1bg1rcieq2suvfbe@indeedemail.com>,1,0,yes-request,emaxwell,action,answer-questions,1
4,5805740-3759,<BN6PR08MB25300D48A531251470C9C642BD780@BN6PR0...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,5805740,<1bgbpbj2o2suvb7b@indeedemail.com>,1,0,yes-request,emaxwell,action,confirm-one-option,1
5,5941549-845,<01d301d30fbf$58a47760$09ed6620$@com>,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,5941549,<1bf1tifc40c8p4ca@indeedemail.com>,1,0,yes-request,jha,action,apply-online,1
6,6505112-804,<DM5PR13MB13698F08AC7ECD696BD3C525BB840@DM5PR1...,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,6505112,<1bgocmjcl2suvf6l@indeedemail.com>,1,1,yes-request,jha,action,confirm-interest,1
7,12696619-470,<SN1PR0801MB156808B3594C717892E930D7B3910@SN1P...,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,12696619,<1bh38n4ue2stiek4@indeedemail.com>,1,1,yes-request,jha,action,apply-online,1
8,12891144-149,<CAJMvtewSm8_r2uo1Ykh0B5TCbrW8Q0TNgnw7kd-q=Ky4...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,12891144,<1bhustq4d2stib4v@indeedemail.com>,1,1,no-request,jha,noaction,marketing-spam},1
9,11931275-20,<1016025201.242192.1499973880814@email.1and1.c...,DRADIS,dradis-reply,en,CA,EMPLOYER,JOBSEEKER,11931275,<1bhlfjju429klb1m684362122668@indeedemail.com>,1,1,yes-request,jha,action,other,1
10,9780365-298,<CALRk2gyzEwVjK6nra2nMdjnEw0fYeueGjc6uQAXOR1ne...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,9780365,<1bigjilgn2te79g1@indeedemail.com>,1,1,no-request,jha,noaction,marketing-spam},1
11,12891144-149,<CAJMvtewSm8_r2uo1Ykh0B5TCbrW8Q0TNgnw7kd-q=Ky4...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,12891144,<1bhustq4d2stib4v@indeedemail.com>,1,1,no-request,jha,"{""norequest""",marketing-spam},1
12,10297075-263,<1bkrrqa1j3265f7c@indeedemail.com>,DRADIS,dradis-reply,en,US,EMPLOYER,JOBSEEKER,10297075,<1bi73uus1324va5r3f3f8948aee1@indeedemail.com>,0,1,yes-request,jha,action,confirm-interest,1
13,9780365-298,<CALRk2gyzEwVjK6nra2nMdjnEw0fYeueGjc6uQAXOR1ne...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,9780365,<1bigjilgn2te79g1@indeedemail.com>,1,1,no-request,jha,"{""norequest""",marketing-spam},1
14,6722359-3846,<8369562482903715847@unknownmsgid>,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,6722359,<1bj0hiec62te7fdd@indeedemail.com>,1,1,yes-request,jha,action,confirm-one-option,1
15,2876229-4580,<df7cde59ff35406994f25441d4a26375@mail2k13ex02...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,2876229,<1bj0ndjsu2te79g4@indeedemail.com>,1,1,yes-request,jha,action,apply-online,1
16,9488240-146,<456029BB1C2B7E4DA9F3542CC70B7E5F415CF445@mbx0...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,9488240,<1bj53jvbg08v11j0@indeedemail.com>,1,1,yes-request,jha,action,confirm-interest,1
17,9688042-530,<CAMYRBaEv1ocMFRC9J7piwd9aySBBgX=Ee-fHdLqoE184...,DRADIS,application-email,en,US,EMPTY,JOBSEEKER,9688042,<1bj6avl8e08v161f@indeedemail.com>,1,1,yes-request,jha,action,appear-in-person,1
18,4051852-2212,<CAAoobGrjoDbohiAanJWoHtsGJUD8aZ1vS-iP6Unzowmk...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,4051852,<1bj8istph2te7bub@indeedemail.com>,1,1,yes-request,jha,action,confirm-multiple-options,1
19,2664704-412,<8C647728-C3A1-413D-88F7-70ADFB8B5266@prosearc...,DRADIS,application-email,en,US,EMPLOYER,JOBSEEKER,2664704,<1bjtdjk6608v14r6@indeedemail.com>,1,1,no-request,jha,noaction,other},1

In [ ]:
iris_trim = iris[['app', 'appContext', 'language', 'country', 'senderRole', 'recipientRole', 'advertiserid', 'imported', 'opened', 'answer', 'action?', 'sub class']]

In [ ]:
outerdf = depth_sort.join(imp_sort, how='outer')

In [ ]:
iris2 = iris
iris2.set_index('refid', inplace=False)

In [ ]:
columns = ['refid', 'messageld', 'app', 'appContext', 'language', 'country', 'senderRole', 'recipientRole', 'advertiserid', 'conversationRef', 'imported', 'opened', 'answer', 'expert', 'action', 'subClass', 'count']
iris2 = iris.reindex(columns=columns)
iris2[columns] = iris2[columns].astype(int)